//Parse this data.

// '?' => now candidates will start to appear.
// '?[label]' => a candidate. if selected, goto label.
// '>>word_ID' => postfix of a word; indicates that word can be added to vocab list. Automatically parsed when load time.
// '[label]' => indicates position of label.
// '->[label]' => goto label.
// '__FIN__' => special line content that can finalize whole conversation.
// '-' => normal line.
//Parsing is always UP-to-DOWN. Sequence never flows after new label.(i.e. if parser incounter new [label], it's malformed data.)
//Cannot goto past label. ==> these features can help finding context.
var testConv = [
    "- First line of context.",
    "- Second line, in sequence.>>Sequence!!",
    "?",
    "?[ONE] First candidate of first choose.",
    "?[TWO] Second candidate,",
    "?[THE] This is third candidate.",
    "[ONE]",
    "- You choosed the First>>ID_of_word candidate!!",
	"- Context will end now.",
    "__FIN__",
    "[TWO]",
    "- You choosed the SECOND>>second candidate!!!",
	"- Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Du",
    "- Now it's time to choose another.",
    "?",
    "?[GGG] Now, there are two candidates.",
    "?[AAA] I'm planning to color candidates by different hue.",
    "[THE]",
    "- You choosed the THIRD candidate!!",
    "- I can do this as long as I want.",
	"- But it's time to end>>CUSTOM_ID_END the context.",
    "__FIN__",
    "[GGG]",
    "- YOU CHOOSED the FIRST one.",
    "->[FINAL]",
    "- 이 대사는 안 나올 거예요.",
    "[FINAL]",
    "- BYE!! context is over.",
	"__FIN__",
	"[AAA]",
	"- This is the longest context branch.",
    "- Time to say goodbye."];

var testContext = [
    "- 안녕하세요! 전 Einstein 교수>>professor 입니다.",
    "?",
    "?[인사] 안녕하세요, 교수님!",
    "[인사]",
    "- 당신의 이름은>>name 무엇입니까?",
    "?",
    "?[이름말하기] 제 이름은 Natasha입니다.",
    "[이름말하기]",
    "- 오, Natasha, 반갑습니다!",
    "- 왜 저를 찾아오셨나요?",
    "?",
    "?[숙제때문에] 숙제에>>homework 대해서 궁금한 게 있습니다.",
    "?[시험때문에] 시험 일정이 어떻게 되나요?",
    "?[출석때문에] 제 출석>>attendance 점수가 이상합니다.",
    "[숙제때문에]",
    "- 숙제는>>homework 다 했나요?",
    "?",
    "?[숙제다함] 숙제를>>homework 다 했습니다.",
    "?[시험준비안함] 아니오, 아직 안 했습니다.",
    "[숙제다함]",
    "- 대단하네요!",
    "- 제 수업 내용이 쉬운>>easy 건가요?",
    "?",
    "?[수업쉬움] 네, 수업이 꽤 쉽습니다.",
    "?[수업어려움] 아니오, 수업이 너무 어렵습니다.",
    "[수업쉬움]",
    "- 그렇다면 숙제가 더 필요하겠네요.",
    "- 제 수업은>>course 어려워야 합니다.",
    "__FIN__",
    "[수업어려움]",
    "- 마음이 아프네요.",
    "- 그러나 숙제를 줄여 줄 생각은 없어요.",
    "- 내일 새로운 숙제가 나올 거예요.",
    "- 수고하세요!",
    "__FIN__",
    "[시험때문에]",
    "- 시험은 다음 주 목요일>>Thursday 입니다.",
    "- 시험 준비는 하고 계신가요?",
    "?",
    "?[시험준비안함] 아니오, 놀고 있습니다.",
    "?[시험준비함] 네, 열심히 하고 있습니다.",
    "[시험준비안함]",
    "- 마음이 아프네요.",
    "- 저는 F를 많이 가지고 있습니다.",
    "- 나눠줄 사람이 한 명 늘어난 것 같군요!",
    "__FIN__",
    "[시험준비함]",
    "- 시험은 꽤 어렵습니다.",
    "- 더 열심히 하세요!",
    "__FIN__",
    "[출석때문에]",
    "- 출석>>attendance 점수는 바꿔드리지 않아요.",
    "- 돌아가세요.",
    "__FIN__"
];